### PR TITLE
fix: python tailwind install and build command not working

### PR DESCRIPTION
**Pull request by rririanto**
* remove WORKDIR /app command that cause error

### CODE REVIEW

**Comment by rririanto** [comment]
Screen Shot 2021-05-18 at 13 46 35

```tailwind_1  | sh: 1: nodemon: not found it cause hot-reload not working because nodemon is not found. ```

I checked and didn't found node_modules installed on the container. and I found that the problem goes on the dockerfile.

**Comment by rririanto** [comment]
This might related with the issues https://github.com/timonweb/django-tailwind/issues/72

**Comment by swdevbali** [comment]
Can't see the hot reload working tho :)
https://youtu.be/c87bOvrgc1s

**Comment by rririanto** [comment]
> Can't see the hot reload working tho :)
> https://youtu.be/c87bOvrgc1s

It might be because of the windows port issues. My pull request fixed docker issues on my mac.

**Comment by rririanto** [comment]
I close this because I still need to investigate on windows.

**Pull request closed without merging**
