### PR TITLE
Fixed the npm not found error !

### PR DESCRIPTION
**Pull request by Dhruvacube**
There are cases where nodejs is installed correctly but still the package couldn't find the npm correctly, this pr aims to fix that!

Do tell me if any changes is required, lol

### CODE REVIEW

**Comment by ayy-em** [comment]
holy shit you man rock @Dhruvacube

**Comment by Dhruvacube** [comment]
> holy shit you man rock @Dhruvacube
> 
> edit: this should totally be merged

thanks mate!

**Comment by Dhruvacube** [comment]
ahhh closed? okay :( T~T

**Comment by timonweb** [comment]
@Dhruvacube it's closed because using `shell=True` is generally a bad idea.

**Pull request closed without merging**
