### PR TITLE
Add JIT compiler support

### PR DESCRIPTION
**Pull request by babbitt**
Hi there, 
Yesterday [Tailwind announced an experimental Just In Time (JIT) compiler.](https://github.com/tailwindlabs/tailwindcss-jit). While it's experimental it appears to be somewhat stable and brings some awesome features. 

I implemented what I believe to be a working implementation of the JIT compiler. That being said, I'm not so well versed in sass so please let me know if it's inefficient to have the `node-sass` run on update or if only `postcss` needs to run (if so I'll make those quick changes)

Since there's no clearcut contribution guide, I'll just do my best to explain the changes:
* Creation of a `app_template_v2_jit` folder to hold the required changes for JIT compilation
* Changing the `npm dev` script to watch for changes across the project (This isn't the most efficient so I could see some improvement here if I have a chance to sit down and better understand postcss & watch)
* Changing the commands file to include initialization for jit projects, as well as a warning to change the `dev` script if they don't use the suggested theme app name.

I understand this is an experimental feature as of right now for tailwind, but I figured the more support the merrier.

### CODE REVIEW

**Comment by babbitt** [comment]
Just added a quick note to the README on how to use the `--jit` flag.

**Comment by AliMejbar** [comment]
I think it could be great to put instructions to change to jit and already existing app , great work 👍🏽

**Comment by babbitt** [comment]
@AliMejbar as requested. It's a pretty straightforward migration.
I should note now re my earlier comment that there are for sure ways to speed up the builds on the fly. The big elephant in the room is the sass build firing off on every save, which is not strictly necessary. I don't have the time right now but if anyone wants to contribute and put together a better version of the dev script I totally welcome them to do so.

Also PS do we know if @timonweb or any of the maintainers actively monitor this project or is the PR the wrong way to go about this?

**Comment by timonweb** [comment]
Hi, yes I saw your PR, sorry didn't have time to process it. Should have some soon, will get back to you.

**Comment by timonweb** [comment]
@babbitt, thanks a lot for the PR. Although I like the feature, it's experimental, and if I merge it now, that would mean I'd have to support it and possible future changes. I would wait a bit until things get more stable on their side.

**Comment by justinmayer** [comment]
The new Tailwind CSS v2.1 release has [merged the JIT engine into core](https://blog.tailwindcss.com/tailwindcss-2-1#jit-engine-in-core), so I imagine this pull request will need to be adjusted to account for that change.

@babbitt: Would you like to take a look at the [JIT mode documentation](https://tailwindcss.com/docs/just-in-time-mode) and adjust your pull request accordingly?

**Comment by timonweb** [comment]
I told you guys it's worth waiting. I think this PR is obsolete now, since the only change that needs to be introduced is the `mode: jit` in config. It would be enough to update README with such information.

**Comment by babbitt** [comment]
@timonweb I agree this can probably be in the Readme. Just a reminder that you would also still have to change the npm dev script in order to refresh whenever a file changes. Otherwise JIT won't work. Don't know if that would be enough changes to merit my previous approach. 
I have my branch up to date with the latest release. You're welcome to either merge if you're still looking to preserve the different setups or just take inspiration for updating the ReadMe.

**Comment by babbitt** [comment]
> The new Tailwind CSS v2.1 release has [merged the JIT engine into core](https://blog.tailwindcss.com/tailwindcss-2-1#jit-engine-in-core), so I imagine this pull request will need to be adjusted to account for that change.
> 
> @babbitt: Would you like to take a look at the [JIT mode documentation](https://tailwindcss.com/docs/just-in-time-mode) and adjust your pull request accordingly?

@justinmayer I'm all up to date on my end. Feel free to use my fork if you need JIT right now. I will note as before that the npm scripts could maybe use some work as I'm not a Node aficionado and the django-tailwind setup is a little more complicated than standard tailwind. If I have a second I'll look into it but no promises.

**Pull request closed without merging**
